const vehicleAPI = [
  {
    id: 1,
    title: "mercedes benz",
    passengerCount: "4 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "4 Doors",
    img: require("../Images/mercedes.png"),
    price: 2500,
    Rating: 4.7,
    ReviewCount: 350,
    location: "chennai",
  },
  {
    id: 2,
    title: "bentley",
    passengerCount: "4 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "4 Doors",
    img: require("../Images/bentley.png"),
    price: 3000,
    Rating: 4.5,
    ReviewCount: 200,
    location: "bengaluru",
  },
  {
    id: 3,
    title: "bmw",
    passengerCount: "2 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "2 Doors",
    img: require("../Images/bmw-car.png"),
    price: 2000,
    Rating: 4.6,
    ReviewCount: 700,
    location: "chennai",
  },
  {
    id: 4,
    title: "audi",
    passengerCount: "4 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "4 Doors",
    img: require("../Images/audi.png"),
    price: 1800,
    Rating: 4.3,
    ReviewCount: 427,
    location: "bengaluru",
  },
  {
    id: 5,
    title: "mini cooper",
    passengerCount: "4 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "2 Doors",
    img: require("../Images/mini cooper.png"),
    price: 1600,
    Rating: 4.4,
    ReviewCount: 890,
    location: "chennai",
  },
  {
    id: 6,
    title: "roll royce",
    passengerCount: "4 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "4 Doors",
    img: require("../Images/rolls royce.png"),
    price: 4000,
    Rating: 4.9,
    ReviewCount: 763,
    location: "chennai",
  },
  {
    id: 7,
    title: "volvo",
    passengerCount: "4 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "4 Doors",
    img: require("../Images/volvo.png"),
    price: 2300,
    Rating: 4.6,
    ReviewCount: 652,
    location: "bengaluru",
  },
  {
    id: 8,
    title: "lexus",
    passengerCount: "4 Passenger",
    gearBox: "Automatic",
    airConditionn: "AC",
    doors: "4 Doors",
    img: require("../Images/lexus.webp"),
    price: 1900,
    Rating: 4.2,
    ReviewCount: 1200,
    location: "bengaluru",
  },
];

export default vehicleAPI;
